### ISSUE TITLE
Excessive link time with MinGW GCC

### ISSUE THREAD

**Issue by boris-kolpackov** [build2-packaging/args#1]
I've noticed that the submitted package (and CI requests before that) took excessively long to link with MinGW GCC causing our build bots to timeout. 

Could you exclude this configuration from building?

**Comment by boris-kolpackov** [comment]
FYI, I've dropped the current submission from queue since it will keep suspending our bots until this issues is fixed.

**Comment by lyrahgames** [comment]
> I've noticed that the submitted package (and CI requests before that) took excessively long to link with MinGW GCC causing our build bots to timeout.

Thank you for noticing!
Strange that again the non-optimized MinGW build on Windows exhibits this kind of behavior.

> Could you exclude this configuration from building?

I have added a few commits, disabled the builds on non-optimized MinGW versions, and done another [CI run](https://ci.stage.build2.org/@79123ea4-f849-48c7-9280-dceda38ac68f?builds=&pv=&th=*&tg=&tc=&pc=&rs=*).
Hopefully, it should work now.

> FYI, I've dropped the current submission from queue since it will keep suspending our bots until this issues is fixed.

Understandable!
I have submitted a new package version to the queue.

**Comment by boris-kolpackov** [comment]
Yes, this seems to have helped, thanks!
