### ISSUE TITLE
Package `README`

### ISSUE THREAD

**Issue by boris-kolpackov** [build2-packaging/args#2]
You've added a package-specific `README`, which is great! (I also assume you will add `package-description-file` mentioning it on the next release).

But I think all this installation under different names is unnecessarily complicated. Here is the recommended setup:

1. Call upstream `README` just `README.md` and call package `README` either `PACKAGE-README.md` or `README-PACKAGE.md`.

2. List them in `manifest`:

```
description-file: README.md
package-description-file: PACKAGE-README.md
```

3. Install them just like that from the root `buildfile`:

```
./: ... doc{README.md PACKAGE-README.md}
```

**Comment by lyrahgames** [comment]
Thanks for pointing that out.
I have always added a `README.md` for the package in addition to the upstream `README.md` when packaging third-party libraries.
My installation strategy is a remnant of the time before the availability of `package-description-file` in build2 v0.16.0 to be able to see the package `README.md` on `cppget.org` to directly show the instructions on how to use the package.
I very much like the `package-description-file` feature and forgot to add it to this package and I already use the strategy you described for other packages I am currently working on.
To clarify: Up to now I am using the name `PACKAGE.README.md` for the package file. Would you rather like me to use `PACKAGE-README.md` instead?

**Comment by boris-kolpackov** [comment]
> I already use the strategy you described for other packages I am currently working on.

Not sure if `happly` is included into this "new" strategy. If it is, then I don't think it matched the new strategy (it still has `USTREAM.README.md`).


> To clarify: Up to now I am using the name PACKAGE.README.md for the package file. Would you rather like me to use PACKAGE-README.md instead?

It's up to you but I think it's a good idea to reserve `.` for extensions that classify the file (e.g., `.md` for markdown) rather than using it as another delimiter (for which I personally prefer `-` but `_` also works).

**Comment by lyrahgames** [comment]
> Not sure if `happly` is included into this "new" strategy. If it is, then I don't think it matched the new strategy (it still has `USTREAM.README.md`).

No, this one still uses the old one.

> It's up to you but I think it's a good idea to reserve `.` for extensions that classify the file (e.g., `.md` for markdown) rather than using it as another delimiter (for which I personally prefer `-` but `_` also works).

I will then use `PACKAGE-README.md' in the future.

**Comment by lyrahgames** [comment]
The last commit should address this issue. When you close the issues, I can also submit the new package version to the queue.

**Comment by boris-kolpackov** [comment]
Looks good, thanks.
