### ISSUE TITLE
Bundled `catch2` is not ideal

### ISSUE THREAD

**Issue by boris-kolpackov** [build2-packaging/args#3]
I noticed that the tests for this library use bundled `catch.hpp`. This is not ideal (but not a deal breaker either) since we have `catch2` as a package (we even have the exact version that is bundled, if this is important for some reason).

Note that switching to the external `catch2` will requite factoring tests into a separate package (`args-tests`) which in turn will require turning this into a multi-package repository. I also see `test.cxx` includes the header without the `<catch2/>` prefix. This can be solved by replacing the upstream `catch.hpp` with a wrapper that simply includes the external header.

**Comment by lyrahgames** [comment]
> I noticed that the tests for this library use bundled `catch.hpp`. This is not ideal (but not a deal breaker either) since we have `catch2` as a package (we even have the exact version that is bundled, if this is important for some reason).

That is funny because I was questioning the same thing while coding it.
It seems so that I have made the wrong decision. I will change that ^^
To explain myself:
The tests of this project are built with this specific header file from Catch2 which could have been altered by the programmers to handle local issues.
So, I thought the I should use their provided version of Catch2 which might be the same as the official.

> Note that switching to the external `catch2` will requite factoring tests into a separate package (`args-tests`) which in turn will require turning this into a multi-package repository. I also see `test.cxx` includes the header without the `<catch2/>` prefix. This can be solved by replacing the upstream `catch.hpp` with a wrapper that simply includes the external header.

I will do this. That is no problem.
I am already using a header wrapper like this for different packages, like chaiscript.

**Comment by boris-kolpackov** [comment]
> The tests of this project are built with this specific header file from Catch2 which could have been altered by the programmers to handle local issues. So, I thought the I should use their provided version of Catch2 which might be the same as the official.

Yes, that would be a valid reason to stick with the bundled version. Unfortunately, I am pretty sure it is bundled not because of the local changes but simply because it is easier. You can always `diff` their header against the official to see if that's the case.

**Comment by lyrahgames** [comment]
> Yes, that would be a valid reason to stick with the bundled version. Unfortunately, I am pretty sure it is bundled not because of the local changes but simply because it is easier. You can always `diff` their header against the official to see if that's the case.

Yeah, of course. I did not think they actually changed something. I was only anticipating the worst case.

I addressed this issue in the last commit and I hope you find the changes to be ok.
You can the find the CI builds [here](https://ci.cppget.org/@d9dfce43-053f-4f18-afbb-3b341558f422).

**Comment by boris-kolpackov** [comment]
Yes, looks reasonable to me.
